### ISSUE TITLE
Newest 2.0.6 version from today 09/10 is not working

### ISSUE THREAD

**Issue by fabiolcf** [dideler/toggle-youtube-comments#1]
The extension has always worked perfectly as intended.

Apparently today the new 2.0.6 update was pushed and... the extension no longer works. It's as if it were not there: having it disabled or enabled leads to exactly the same result on youtube.

**Comment by fabiolcf** [comment]
As of today 9/14 , the issue seems to have disappeared. Version has updated to 2.0.7

**Comment by dideler** [comment]
Hey @fabiolcf, thanks for the report. For some reason I didn't see a notification that this issue was created. Hope you're still enjoying the extension, and let us know if you have any more feedback.
