### ISSUE TITLE
Japanese translations

### ISSUE THREAD

**Issue by 1natsu172** [dideler/toggle-youtube-comments#15]
I'm Japanese, so think will translate extension.
I'm thinking what to do with webstore sentences ... 🤔 

<img width="971" alt="2017-12-28t18-48-49" src="https://user-images.githubusercontent.com/7282145/34407119-25c2a75e-ec00-11e7-98bb-b7ea29c8ff77.png">

***

For now, I'll translate the parts of the "SHOW COMMENTS" button. I'll send PullRequest later.

![2017-12-28 18 49 18](https://user-images.githubusercontent.com/7282145/34407123-2be04376-ec00-11e7-85fe-cdf03980bc5e.png)

like this ☝️

**Comment by dideler** [comment]
Great idea!

The webstore description can only be changed by the publisher(s) via the web UI, see https://developer.chrome.com/webstore/i18n#longDescription. I can upload any provided translations for the webstore if they're shared here.

Sometimes literal translations do not communicate a message well. You're welcome to rewrite any content in the description to be more relevant for a Japanese audience.

**Comment by 1natsu172** [comment]
Thanks @dideler .

I understand that it can be changed only on publisher's Web UI.
So i created a Japanese webstore description so please upload with the following sentences.

👇 

```
この拡張機能を追加すると、YouTubeのコメント欄の表示/非表示ができるようになります。

 • 新デザイン・旧デザイン両方のYouTubeで動作
 • コメント欄の柔軟な表示切り替えが可能
 • YouTubeのUIに馴染むデザイン
 • ユーザーのプライバシーを尊重：トラッキングしません
 • とても軽量な拡張機能：肥大化しません
 • メンテナンスサポート継続中
 • オープンソースコードです

リリースノートはこちら: https://git.io/v5RgW

Icon by Gregor Cresnar (Creative Commons).
```

👆 

By the way, I translated the description into more relevant Japanese as much as possible.
It's OK if you have time, so please apply it to Japanese description. 🙏

**Comment by dideler** [comment]
I've applied the Japanese description for the webstore. It might take some time to show. Thank you!

**Comment by dideler** [comment]
For v2.5.0 I've added a new line to the long description.

>  • Shows number of comments when hidden

Google Translate gives this Japanese translation but I don't know how good it is:

> • 非表示のコメントの数を表示する

**Comment by 1natsu172** [comment]
Checked the additional description. So I revised Japanese translation and made it better description (even include a new description line).
I rewritten the whole sentence so I want to change the all.

👇 
```
この拡張機能を追加すると、YouTubeのコメント欄の表示/非表示ができるようになります。

 • 新デザイン&旧デザイン両方のYouTubeに対応
 • コメント欄の表示/非表示ボタンを提供
 • YouTubeのUIに馴染むボタンデザイン
 • ボタンにコメント数を表示(コメント非表示時のみ)
 • ユーザーのプライバシーを尊重 - トラッキングコードなし
 • 軽量設計の低サイズ拡張機能
 • メンテナンス&サポート継続中
 • オープンソースコード

リリースノートはこちら: https://git.io/v5RgW
```

**Comment by dideler** [comment]
Updated, thanks!

**Comment by 1natsu172** [comment]
Hi @dideler , today I localized the screen shot of chrome web store to Japanese version.

Japanese srore URL is this.

https://chrome.google.com/webstore/detail/toggle%C2%A0youtube%C2%A0comments/ampjnmipdgicjjidohpkidhghakoidfm?hl=ja

So it may take time to apply the change.

The report is over! 📔

**Comment by dideler** [comment]
The localised screenshots are now live, fantastic! Thanks @1natsu172. Closing #28.
