### ISSUE TITLE
Old YouTube Comments bug

### ISSUE THREAD

**Issue by 1natsu172** [dideler/toggle-youtube-comments#16]
Cause of PR #12 

sorry! 🙇 
There was a bug in OLDYOUTUBE due to the change I submitted…

<img width="656" alt="2017-12-28t19-06-47" src="https://user-images.githubusercontent.com/7282145/34407676-05f1e842-ec03-11e7-9a17-a7642a4b13ae.png">

I'll submit a PR of the correction later.

**Comment by dideler** [comment]
Fixed in 2bc680fd3c159189e94720a4fa46cad827301fda
