### ISSUE TITLE
Include code changes in release notes

### ISSUE THREAD

**Issue by dideler** [dideler/toggle-youtube-comments#27]
We currently have release notes under our [releases page][releases], which is great for the average user. But technical users are also interested in the source changes, which we don't cover well at the moment. We should start including a commit range in every release. We can backfill existing releases.

Normally such stuff would live in a CHANGELOG. But I'm hesitant to add a CHANGELOG in addition to the [Releases][releases] because it creates more process by having to put release notes in two places. If we do decide to have a CHANGELOG, one option is to keep it empty and have it link to the Releases.

[releases]: https://github.com/dideler/toggle-youtube-comments/releases

**Comment by dideler** [comment]
Started updating Releases using a comparison between tags such as `https://github.com/dideler/toggle-youtube-comments/compare/<old-tag>...<new-tag>`

Have to head out for a bit, still have a few more to go before we can close this ticket.

**Comment by dideler** [comment]
Backfilled the change comparison on all Releases.

Note the comparisons for the first two releases did not play well with tags, so had to use commit SHAs instead.

**Comment by 1natsu172** [comment]
Great work! And thanks!
Although I couldn't think of it, tag comparison is a very good solution! 👍
