### ISSUE TITLE
Hosted assets

### ISSUE THREAD

**Issue by dideler** [dideler/toggle-youtube-comments#32]
Place all assets that aren't under version control inside this thread.

This "issue" is only marked as closed so it doesn't appear as noise between real open issues.

**Comment by dideler** [comment]
English screenshots used at v2.0.0 (640x400)

![1](https://user-images.githubusercontent.com/497458/35769665-2316d8a4-0906-11e8-8304-eaed7adc2ae4.jpg)

![2](https://user-images.githubusercontent.com/497458/35769668-283551b2-0906-11e8-846c-2772eeeb4520.jpg)

![3](https://user-images.githubusercontent.com/497458/35769670-2c7c51a8-0906-11e8-97c7-acc0d5dca99e.jpg)

**Comment by dideler** [comment]
English screenshots used at v2.5.0 (1280x800)

<img width="640" alt="toggle-yt-comments-show" src="https://user-images.githubusercontent.com/497458/35769692-864a06c6-0906-11e8-8ea0-4c0a168f7357.png">

<img width="640" alt="toggle-yt-comments-hide" src="https://user-images.githubusercontent.com/497458/35769696-956fbf92-0906-11e8-9b91-75964d2fe9f2.png">

<img width="640" alt="toggle-old-yt-comments-show" src="https://user-images.githubusercontent.com/497458/35769699-a9574610-0906-11e8-871c-9963b746f8b5.png">

**Comment by 1natsu172** [comment]
Japanese screenshots used at v2.5.0 (1280x800)

![](https://i.gyazo.com/347255dd9394ef02cb1d6925c76a400f.png)
![](https://i.gyazo.com/20e76b4f020c7352d9f75bb5e19929ae.png)
![](https://i.gyazo.com/e52707c121d2069f6cac52f2561b8471.png)

…Capture words too small, so I think to recapture with 200% zoom 🤔

**Comment by dideler** [comment]
I like the dim and highlight that you've used to focus the attention on the button!

**Comment by 1natsu172** [comment]
Thanks! What kind of OS are you using? If MacOS X, you can edit from Preview.app in 3 steps!

![2018-02-05 14 35 32](https://user-images.githubusercontent.com/7282145/35789860-84d9655c-0a82-11e8-8669-9557e59caae0.png)

**Comment by dideler** [comment]
![Chrome Web Store](https://user-images.githubusercontent.com/497458/42402524-3cbe146c-8173-11e8-9e68-8c01ab968e77.png)

Source: https://developer.chrome.com/webstore/images/ChromeWebStore_Badge_v2_340x96.png
