### ISSUE TITLE
Make it easier to release a new version

### ISSUE THREAD

**Issue by dideler** [dideler/toggle-youtube-comments#36]
Even though we have a build process, there's still a lot of manual [release steps](https://github.com/dideler/toggle-youtube-comments/blob/master/CONTRIBUTING.md#release).

It would be nice to have easier version bumps, for example

```
make version <newversion> | major | minor | patch
```

Nice to haves
- If run in a git repo, it will also create a version commit and tag
- If supplied with a description option, will use it as a commit message body
- Creates annotated tag with "commit changes" (as a template for GitHub Releases)

(Note the example uses Make but this applies to any build system we end up using long term.)

**Comment by 1natsu172** [comment]
📝  Util libraries is these.

* [version-bump-prompt](https://github.com/BigstickCarpet/version-bump-prompt)
* [releasy](https://github.com/vtex/releasy)
* [bumped](https://github.com/bumped/bumped)

I haven't tried any of them yet. But 'bumped' feels good. As we can have config with `yml` or `json`, it seems easy to manage release messages. Also, 'bumped' seems to be able to specify other files of `packgae.json`. We also have to bump `manifest.json`.

**Comment by 1natsu172** [comment]
hmmm, I tried locally 'bumped' but I got an npm error... when `bumped init` then then` bumped version` 🤔  If this isn't my problem only, it may not be good.

---

【Additional notes】
I asked the question with 'bumped' issue and it was fixed by the author!
'bumped' is working now without problems.

**Comment by 1natsu172** [comment]
There were also some other nice automatic release libraries.

* [ZEIT - Release](https://github.com/zeit/release)
* [Semantic-release](https://github.com/semantic-release/semantic-release)
* [release-it](https://github.com/webpro/release-it)

Considering the creation of the GitHub release, is it better to use these than 'bumped'?

**Comment by dideler** [comment]
Thanks to #37, [npm-version](https://docs.npmjs.com/cli/version) is now an option.

We can extend `npm-version` with `preversion`, `version`, or `postversion` scripts. I think we should try this standard approach first and if it's not good enough, then we can try a third party library or build something custom.

**Comment by 1natsu172** [comment]
Well, the `npm version *` command is certainly useful. It also git commit and create tag. If we use the `postversion` command, can automatically push these.

```json
"scripts": {
    "version": "(BUMP MANIFEST.JSON PROCESS) && git add .",
    "postversion": "git push && git push --tags",
    "bump:patch": "npm version patch -m \":arrow_up: Bump version to %s\"",
    "bump:minor": "npm version minor -m \":arrow_up: Bump version to %s\"",
    "bump:major": "npm version major -m \":arrow_up: Bump version to %s\""
}
```

We can attach a commit message with the `-m` option, but in order to attach the same commit message to menifest.json's bump process at the same time, we have to do as above. but I think it's too hard to just write the `manifest.json` bump process on the single line here. Because we write code to get "version" value of `package.json` and regex condition and rewrite "version" of `manifest.json`. 

I think that it is better to divide it into processing file like `tasks/bumpmanifest.js` 🤔  How do you feel?

**Comment by dideler** [comment]
@1natsu172 please take a look at #38 🙏

I didn't include the `bump:*` scripts. It would limit our bumping capabilities to a subset of `npm-version` features, and also introduces a non-standard way of bumping (e.g. `npm run bump:minor` vs `npm version minor`) for little benefit. We can manually pass the `-m` option if we want to continue having commits consistent with the older version bumps, but I'm also okay with the new and plain `vX.Y.Z` commit messages.

I've created #39 for some potential follow-up improvements.

**Comment by 1natsu172** [comment]
@dideler thanks for #38 .

I was writing the `bump: *` command to make the commit message easier. But if you manually `-m` or allow plain` vX.Y.Z`, I think that is OK! 👍
