### ISSUE TITLE
Port to Firefox?

### ISSUE THREAD

**Issue by Commenter25** [dideler/toggle-youtube-comments#43]
I'm interested in this extension, however I use Firefox and can't use it.

Porting to Firefox has been made much easier with the WebExtensions API, so I imagine it wouldn't be too hard, and it would open up a whole new user-base.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by dideler** [comment]
Hi @CommenterOfComments, thanks for your interest.

I don't use Firefox much and have no interest in porting it at this point.

But I'm happy for others to create a Firefox port as long as attribution to the original is given.

**Comment by Commenter25** [comment]
Ah, alright. I can understand. Thanks for replying!
