### ISSUE TITLE
Button not being injected on New YouTube

### ISSUE THREAD

**Issue by dideler** [dideler/toggle-youtube-comments#44]
This evening it stopped working, likely due to some new changes that YouTube deployed.

![image](https://user-images.githubusercontent.com/497458/56990057-f49bfb00-6b8b-11e9-937a-8391aecf8aab.png)

**Comment by 1natsu172** [comment]
Broken reason is probably can't await `more` button rendered.

https://github.com/dideler/toggle-youtube-comments/blob/b6245d4c20604736c3698c36f65667d01023f3fd/src/script.js#L200

I saw 'yt-register-action' event for hotfix, but I did not find an event that would apply to the Meta panel's render.

There is no solution at the moment. 🤷‍♂

**Comment by 1natsu172** [comment]
@dideler I'm working on the correction again.

**Comment by 1natsu172** [comment]
@dideler 

Completed fix now.

Already released [v4.1.3](https://github.com/dideler/toggle-youtube-comments/releases/tag/v4.1.3) on both Master branch and Chrome Web Store without approval because it is a hot fix. 🙏 

Sorry for your inconvenience, but please update the local branch.

**Comment by dideler** [comment]
@1natsu172 you're amazing, thanks for fixing!

 :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
