### ISSUE TITLE
Minify extension

### ISSUE THREAD

**Issue by dideler** [dideler/toggle-youtube-comments#5]
[When the extension is bundled](../blob/master/bundle.sh), we can minify as many things as possible (e.g. HTML, JSON, JS, CSS, icons, images). This will make the published version even more lightweight and a reduced size, even if minimal, is better for the network and our users' devices.

**Comment by 1natsu172** [comment]
* [Parcel](https://github.com/parcel-bundler/parcel)
  * Zero config & fast
  * but may not be suitable for projects without HTML…?
* [webpack4](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2)
  * Zero config available
  * Now beta, a stable version will be released sometime soon.
  * but may not be suitable because this is huge.
* npm scripts + some minify libraries
  * Directly use libraries
* Gulp+Gulp plugins
* Use one of the ChromeExtension starter kits

There are several methods, but many features are unnecessary. We should adopt what is easy to use and not bothersome.
Since this project is Chrome extension, we'll not need transpiles unless we're using the latest ES-stages.

Anyway, there are many approaches.

**Comment by dideler** [comment]
Thanks for doing some investigation. A few months ago I was looking at [minify](https://github.com/tdewolff/minify/tree/master/cmd/minify). I'll hack up something on a branch to give an idea of how it could be used in the current build process. But I don't like the barrier of installation, a JS solution would probably be a bit friendlier for someone to get started.

**Comment by 1natsu172** [comment]
[minify](https://github.com/tdewolff/minify/tree/master/cmd/minify) is seem to simple & useful (must be ready "go" lang…). However, I have looked at JS compression solution of 'minify', but JSMin is used. I think this is a bit old and not cool. It doesn't support minify of ES2015+ . So, recently [uglify-es(Uglify-JS3)](https://github.com/mishoo/UglifyJS2) is mainly used for ES2015+.

Nonetheless, I think that 'minify' will be compressed from the current size. I think that it's not a bad choice. 

Let's choose the one that is easy to use and the best for us after more discussion. I also try some solutions on the branch.

**Comment by dideler** [comment]
> I have looked at JS compression solution of 'minify', but JSMin is used. I think this is a bit old and not cool. It doesn't support minify of ES2015.

Good spot, thanks for investigating.

PR #34 shows example usage of how minify could be used in the current build process. It feels a bit clunky to install and use, and the results are not so good. But I do like that it feels like a lightweight solution compared to a heavy JS solution that would depend on npm, node, and very many packages.

However, the end user is not exposed to the build process, so it doesn't really matter how light or heavyweight that part is. I think the best option will be the one that gives the user the smallest size extension, and is the easiest for contributors to use.

A benefit of a JS solution is that we can easily build on top of npm scripts for a build process which many developers are used to, instead of Make which isn't as accessible to developers because it's a less popular tool that many people aren't familiar with.

**Comment by 1natsu172** [comment]
Thank you for testing 'minify' ! Although the result seems not to be good... 🤔 

But, I fully agree with your opinion. 

>best option will be the one that gives the user the smallest size extension, and is the easiest for contributors to use.

As you said, the best option is to provide user with bundled extensions of minimal size, and prepare what contributors can easily develop.

I'm not ready for JS solution yet, but I'd like to submit a branch in a few days.

**Comment by 1natsu172** [comment]
@dideler , I implemented JS solution and submitted PR. This is the state of v2.5.2. Please check it when you have time!

Details are written in PR (#37) 🙏

**Comment by dideler** [comment]
Resolved in a3f738ce4e198146c4edd106d30a6ca73ea9e926. Thank you for this big contribution! Releasing it as a part of v3.0.0.
